### ISSUE TITLE
你项目放什么服务器上面的  卡的要死

### ISSUE THREAD

**Issue by vipcolud** [xpsilvester/Project#1]

**Comment by xpsilvester** [comment]
有多个项目啊，你运行卡的是哪个

**Comment by vipcolud** [comment]
https://www.xpsilvester.com/demo/WebMoblie/index.html

**Comment by xpsilvester** [comment]
这个啊，就一个响应式页面而已，页面里面的链接进去是用Hexo和github.io搭建的个人网站，服务器应该是github的，手机端的话是有点卡
